name: 'gh-merge-base-next Action'
description: 'Automatically find the next commit on the first-parent path from merge-base.'
author: 'srz-zumix'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    default: ${{ github.token }}
    required: false
  repository:
    description: 'The repository in the format owner/repo. If not provided, the repository of the workflow run is used.'
    default: ''
    required: false
  base:
    description: 'The base ref (branch or commit SHA) to find the merge base from.'
    required: true
  head:
    description: 'The head ref (branch or commit SHA) to find the merge base to.'
    required: true

outputs:
  sha:
    description: 'The SHA of the next commit on the first-parent path from the merge-base.'
    value: ${{ steps.merge-base-next.outputs.sha }}
  depth:
    description: 'The number of commits between the merge-base and the next commit on the first-parent path.'
    value: ${{ steps.merge-base-next.outputs.depth }}

runs:
  using: 'composite'
  steps:
    - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
      with:
        aqua_version: v2.53.9
        # policy_allow: aqua-policy.yaml
        working_directory: ${{ github.action_path }}
    - name: gh-merge-base-next path
      id: gh-merge-base-next
      shell: bash
      env:
        GH_HOST: github.com
        GH_TOKEN: ""
        GH_ENTERPRISE_TOKEN: ""
        AQUA_POLICY_CONFIG: aqua-policy.yaml
      run: |
        gh-merge-base-next --version
        echo "path=$(aqua which gh-merge-base-next)" >> "${GITHUB_OUTPUT}"
      working-directory: ${{ github.action_path }}
    - name: merge-base-next
      id: merge-base-next
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.repo-token }}
        GH_ENTERPRISE_TOKEN: ${{ inputs.repo-token }}
        INPUTS_REPOSITORY: ${{ inputs.repository }}
        INPUTS_BASE: ${{ inputs.base }}
        INPUTS_HEAD: ${{ inputs.head }}
        GH_MERGE_BASE_NEXT: ${{ steps.gh-merge-base-next.outputs.path }}
      run: |
        MERGE_BASE_NEXT_OPTIONS=()
        if [ -n "${INPUTS_REPOSITORY}" ]; then
          MERGE_BASE_NEXT_OPTIONS+=(--repo "${INPUTS_REPOSITORY}")
        fi
        set -x
        "${GH_MERGE_BASE_NEXT}" \
          --base "${INPUTS_BASE}" --head "${INPUTS_HEAD}" \
          --format json \
          --template 'sha={{ .sha }}{{ "\n" }}depth={{ .depth }}{{ "\n" }}' \
          "${MERGE_BASE_NEXT_OPTIONS[@]}" >> "${GITHUB_OUTPUT}"

branding:
  icon: 'git-branch'
  color: 'purple'
